apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: loki-logging
  labels:
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: loki-logging
    meta.helm.sh/release-namespace: loki-logging
data:
  config.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
    ingester:
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
        final_sleep: 0s
      chunk_idle_period: 5m
      max_chunk_age: 1h
    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
    storage_config:
      boltdb_shipper:
        active_index_directory: /loki/index
        cache_location: /loki/index
        shared_store: filesystem
      filesystem:
        directory: /loki/chunks
    compactor:
      working_directory: /loki/compactor
      shared_store: filesystem
    limits_config:
      enforce_metric_name: false
    chunk_store_config:
      max_look_back_period: 0s
    table_manager:
      retention_deletes_enabled: true
      retention_period: 168h
