apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: loki-logging
  labels:
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: loki-logging
    meta.helm.sh/release-namespace: loki-logging
spec:
  selector:
    app: loki
  ports:
    - name: http
      port: 3100
      targetPort: 3100
