apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-logs-gcp-config
  namespace: gcp-logging-system
  labels:
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: gcp-k8s-logging
    meta.helm.sh/release-namespace: gcp-logging-system
data:
  config.alloy: |
    discovery.kubernetes "pods" {
      role = "pod"
    }

    discovery.relabel "pods" {
      targets = discovery.kubernetes.pods.targets
      rule {
        source_labels = ["__meta_kubernetes_namespace", "__meta_kubernetes_pod_name"]
        target_label = "namespace_pod"
        separator = "/"
        replacement = "$1/$2"
      }
    }

    loki.source.file "pod_logs" {
      targets = discovery.relabel.pods.output
      forward_to = [google.logging.default.receiver]
      pipeline {
        stage.match {
          selector = "{}"
          stage.regex {
            expression = "^(?P<log>.*)$"
          }
          stage.labels {
            values = {
              job       = "kubernetes-pod-logs",
              namespace = "{{.namespace}}",
              pod       = "{{.pod}}",
            }
          }
        }
      }
    }

    google.logging "default" {
      project_id = "my-infra-project-id"
      log_name   = "kubernetes-pod-logs"
    }
