apiVersion: v1
kind: Secret
metadata:
  name: grafana-k8s-monitoring-values
  namespace: grafana-monitoring-system
  labels:
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: grafana-k8s-monitoring
    meta.helm.sh/release-namespace: grafana-monitoring-system
type: Opaque
stringData:
  values.yaml: |
    cluster:
      name: suncoast-systems-k8s-cluster

    destinations:
      - name: grafana-cloud-metrics
        type: prometheus
        url: https://prometheus-prod-56-prod-us-east-2.grafana.net/api/prom/push
        auth:
          type: basic
          username: "2361797"
          password: "glc_eyJvIjoiMTM5NDAyMCIsIm4iOiJzdGFjay0xMjE4Nzc5LWludGVncmF0aW9uLXN1bmNvYXN0LXN5c3RlbXMtazhzLWNsdXN0ZXItdG9rZW4tc3VuY29hc3Qtc3lzdGVtcy1rOHMtY2x1c3Rlci10b2tlbiIsImsiOiI5azVSR0w1OHVYeU9FdDM2VDc0eU0zMnkiLCJtIjp7InIiOiJwcm9kLXVzLWVhc3QtMCJ9fQ=="

    clusterMetrics:
      enabled: true
      kubeStateMetrics:
        enabled: true
      nodeExporter:
        enabled: true
        relabelConfigs:
          - source_labels: ["__name__"]
            regex: "node_filesystem_(avail|size|free|used)_bytes|node_filesystem_files"
            action: keep
      opencost:
        enabled: false
      kepler:
        enabled: false

    clusterEvents:
      enabled: false
    nodeLogs:
      enabled: false
    podLogs:
      enabled: false
    applicationObservability:
      enabled: false
    autoInstrumentation:
      enabled: false

    alloy-metrics:
      enabled: true
      alloy:
        remoteConfig:
          enabled: false