apiVersion: v1
kind: Secret
metadata:
  name: grafana-k8s-monitoring-values
  namespace: grafana-monitoring-system
  labels:
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: grafana-k8s-monitoring
    meta.helm.sh/release-namespace: grafana-monitoring-system
type: Opaque
stringData:
  values.yaml: |
    cluster:
      name: suncoast-systems-k8s-cluster

    kubeStateMetrics:
      enabled: true

    destinations:
      - name: grafana-cloud-metrics
        type: prometheus
        url: https://prometheus-prod-56-prod-us-east-2.grafana.net/api/prom/push
        auth:
          type: basic
          usernameFromEnvVar: METRICS_USERNAME
          passwordFromEnvVar: METRICS_PASSWORD

      - name: grafana-cloud-logs
        type: loki
        url: https://logs-prod-036.grafana.net/loki/api/v1/push
        auth:
          type: basic
          usernameFromEnvVar: LOGS_USERNAME
          passwordFromEnvVar: LOGS_PASSWORD

      - name: grafana-cloud-traces
        type: otlp
        url: https://tempo-prod-26-prod-us-east-2.grafana.net
        protocol: grpc
        auth:
          type: basic
          usernameFromEnvVar: TRACES_USERNAME
          passwordFromEnvVar: TRACES_PASSWORD
        metrics:
          enabled: false
        logs:
          enabled: false
        traces:
          enabled: true

    clusterMetrics:
      enabled: true
      opencost:
        enabled: true
        metricsSource: grafana-cloud-metrics
        opencost:
          exporter:
            defaultClusterId: suncoast-systems-k8s-cluster
          prometheus:
            existingSecretName: grafana-cloud-metrics-grafana-k8s-monitoring
            external:
              url: https://prometheus-prod-56-prod-us-east-2.grafana.net/api/prom
      kepler:
        enabled: false

    clusterEvents:
      enabled: true

    nodeLogs:
      enabled: false

    podLogs:
      enabled: true

    applicationObservability:
      enabled: true
      receivers:
        otlp:
          grpc:
            enabled: true
            port: 4317
          http:
            enabled: true
            port: 4318
        zipkin:
          enabled: true
          port: 9411
      connectors:
        grafanaCloudMetrics:
          enabled: true
    autoInstrumentation:
      enabled: false

    alloy-metrics:
      enabled: true
      alloy:
        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        metrics:
          configs:
            - name: trim-unneeded-metrics
              scrape_configs:
                - job_name: 'node'
                  metric_relabel_configs:
                    - source_labels: [fstype]
                      regex: "tmpfs|devtmpfs|overlay"
                      action: drop
                - job_name: 'kubelet'
                  metric_relabel_configs:
                    - source_labels: [container]
                      regex: "POD|pause|"
                      action: drop
        extraEnv:
          - name: METRICS_USERNAME
            valueFrom:
              secretKeyRef:
                name: grafana-k8s-monitoring-secrets
                key: metrics_username
          - name: METRICS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: grafana-k8s-monitoring-secrets
                key: metrics_password
          - name: GCLOUD_RW_API_KEY
            valueFrom:
              secretKeyRef:
                name: grafana-k8s-monitoring-secrets
                key: gcloud_rw_api_key
          - name: REMOTECONFIG_USERNAME
            valueFrom:
              secretKeyRef:
                name: grafana-k8s-monitoring-secrets
                key: remoteconfig_username
          - name: REMOTECONFIG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: grafana-k8s-monitoring-secrets
                key: remoteconfig_password
          - name: CLUSTER_NAME
            value: suncoast-systems-k8s-cluster
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: GCLOUD_FM_COLLECTOR_ID
            value: grafana-k8s-metrics-$(CLUSTER_NAME)-$(NAMESPACE)-$(POD_NAME)
        remoteConfig:
          enabled: true
          url: https://fleet-management-prod-008.grafana.net
          auth:
            type: basic
            usernameFromEnvVar: REMOTECONFIG_USERNAME
            passwordFromEnvVar: REMOTECONFIG_PASSWORD

    alloy-singleton:
      enabled: true
      alloy:
        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        extraEnv:
          - name: GCLOUD_RW_API_KEY
            valueFrom:
              secretKeyRef:
                name: grafana-k8s-monitoring-secrets
                key: gcloud_rw_api_key
          - name: REMOTECONFIG_USERNAME
            valueFrom:
              secretKeyRef:
                name: grafana-k8s-monitoring-secrets
                key: remoteconfig_username
          - name: REMOTECONFIG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: grafana-k8s-monitoring-secrets
                key: remoteconfig_password
          - name: CLUSTER_NAME
            value: suncoast-systems-k8s-cluster
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: GCLOUD_FM_COLLECTOR_ID
            value: grafana-k8s-singleton-$(CLUSTER_NAME)-$(NAMESPACE)-$(POD_NAME)
        remoteConfig:
          enabled: true
          url: https://fleet-management-prod-008.grafana.net
          auth:
            type: basic
            usernameFromEnvVar: REMOTECONFIG_USERNAME
            passwordFromEnvVar: REMOTECONFIG_PASSWORD

    alloy-logs:
      enabled: true
      alloy:
        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        config:
          logs:
            config:
              feature.pod_logs:
                discovery.relabel.filtered_pods_with_paths:
                  rules:
                    - source_labels:
                        - __meta_kubernetes_namespace
                        - __meta_kubernetes_pod_name
                        - __meta_kubernetes_pod_uid
                        - __meta_kubernetes_pod_container_name
                      separator: "_"
                      action: replace
                      replacement: "/var/log/pods/$1_$2_$3/$4/*.log"
                      target_label: __path__
              feature.node_logs:
                journal_path: /var/log/journal
                matchers:
                  - "_SYSTEMD_UNIT=kubelet.service"
                  - "_SYSTEMD_UNIT=containerd.service"
                  - "_SYSTEMD_UNIT=networkd-dispatcher.service"
        extraEnv:
          - name: LOGS_USERNAME
            valueFrom:
              secretKeyRef:
                name: grafana-k8s-monitoring-secrets
                key: logs_username
          - name: LOGS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: grafana-k8s-monitoring-secrets
                key: logs_password
          - name: GCLOUD_RW_API_KEY
            valueFrom:
              secretKeyRef:
                name: grafana-k8s-monitoring-secrets
                key: gcloud_rw_api_key
          - name: REMOTECONFIG_USERNAME
            valueFrom:
              secretKeyRef:
                name: grafana-k8s-monitoring-secrets
                key: remoteconfig_username
          - name: REMOTECONFIG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: grafana-k8s-monitoring-secrets
                key: remoteconfig_password
          - name: CLUSTER_NAME
            value: suncoast-systems-k8s-cluster
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: GCLOUD_FM_COLLECTOR_ID
            value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-alloy-logs-$(NODE_NAME)
        remoteConfig:
          enabled: true
          url: https://fleet-management-prod-008.grafana.net
          auth:
            type: basic
            usernameFromEnvVar: REMOTECONFIG_USERNAME
            passwordFromEnvVar: REMOTECONFIG_PASSWORD
        volumeMounts:
          - name: journal
            mountPath: /var/log/journal
            readOnly: true
        volumes:
          - name: journal
            hostPath:
              path: /var/log/journal

    alloy-receiver:
      enabled: true
      alloy:
        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        extraPorts:
          - name: otlp-grpc
            port: 4317
            targetPort: 4317
            protocol: TCP
          - name: otlp-http
            port: 4318
            targetPort: 4318
            protocol: TCP
          - name: zipkin
            port: 9411
            targetPort: 9411
            protocol: TCP
        extraEnv:
          extraEnv:
          - name: GCLOUD_RW_API_KEY
            valueFrom:
              secretKeyRef:
                name: grafana-k8s-monitoring-secrets
                key: gcloud_rw_api_key
          - name: CLUSTER_NAME
            value: suncoast-systems-k8s-cluster
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: GCLOUD_FM_COLLECTOR_ID
            value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-alloy-receiver-$(NODE_NAME)
        remoteConfig:
          enabled: false
