apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-agent
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-agent
  template:
    metadata:
      labels:
        app: grafana-agent
    spec:
      containers:
      - name: agent
        image: grafana/agent:v0.40.3
        args:
          - "--config.file=/etc/agent/agent.yaml"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        volumeMounts:
          - name: config
            mountPath: /etc/agent
      volumes:
        - name: config
          configMap:
            name: grafana-agent-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-agent-config
  namespace: monitoring
data:
  agent.yaml: |
    metrics:
      global:
        scrape_interval: 15s
      configs:
        - name: default
          scrape_configs:
            - job_name: 'dcgm'
              static_configs:
                - targets: ['nvidia-dcgm-exporter.nvidia.svc.cluster.local:9400']
          remote_write:
            - url: https://prometheus-prod-56-prod-us-east-2.grafana.net/api/prom/push
              basic_auth:
                username: "2361797"
                password: "glc_eyJvIjoiMTM5NDAyMCIsIm4iOiJzdGFjay0xMjE4Nzc5LWFsbG95LXN1bmNvYXN0LXN5c3RlbXMtZ3B1LXRva2VuIiwiayI6Im03OHNJSDFmSDdqN05EZ1RWMDM5c2c3NiIsIm0iOnsiciI6InByb2QtdXMtZWFzdC0wIn19"