
apiVersion: fleet.cattle.io/v1alpha1
kind: Bundle
metadata:
  name: loki-logging
spec:
  resources:
    - configmap.yaml
    - deployment.yaml
    - service.yaml

dependsOn:
  - name: 01-gcp-logging-namespace
    namespace: kube-system
  - name: 02-gcp-logging-secrets
    namespace: gcp-logging-system
  - name: 03-gcp-logging-config
    namespace: gcp-logging-system
  - name: 06-loki-namespace
    namespace: kube-system
