apiVersion: v1
kind: Secret
metadata:
  name: gcp-logging-creds
  namespace: gcp-logging-system
  labels:
      app.kubernetes.io/managed-by: Helm
      meta.helm.sh/release-name: gcp-k8s-logging
      meta.helm.sh/release-namespace: gcp-logging-system
type: Opaque
stringData:
  key.json: |
    {
      "type": "service_account",
      "project_id": "suncoast-systems-infra-0e1b",
      "private_key_id": "be72f8d6ddf8e28b9f5d8cbefe0e3060055b6421",
      "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDjV6TD5PNzcsMf\ncIq6hbYm4Kf7vhNBzZ/Z9UhR3f2LxVVrimRZA1Kwny7G0kqWWfRRrLVHwYfLyiLz\n5mMQ3bnZYbhmdGodbk/1eYWn8w6bSAiCNj5t3B5cGWPB89Br0Qt07jwFTi95D2Q/\nHIDT2t4NcyqCs4WTTny8CoC4D50wNcR4+5/1W3zZdNuZEKaHyf9yw7AsSgQfwOvD\nCI7w5GCebJdrxWpOmel3ruPa5Y5yWqWY20y4rUKCT3NshJz9cxTUP/fustIzWaYl\n8Rl3+qIQ5y4twO6Dh1/X0R+BCqPMhuh5XOeyMzGrvSX0U27nUczny8sdqGH1Zqn/\nTpgXXyyhAgMBAAECggEAFBryT4AQxv3NY3CSAZMv++SJUUT1h1prz8br6ZA5deId\nPvX4ZZDa1WjhJk8prn3vvUYKACRi4d29/+uOM6B66PkbPuBTvseR2wfaD0jPsAw2\nSGxgqAQ79nF+YNmIQ0izpoMnxrZWkh0PhK9SIKpDUgAvMGuM8sKRsGrjXaPFMc1H\nfOhHCOv+4lGY/MovbFmCuRFIoiKx1HbVcVM4IbicDtDdeyBOUahg/5tVGiW8PJ/T\n9zrR0TdswEaq8g8Jbldx7ZF2gRpEsiW0Y6Vl4Fie18rRaqIItv4cHK55PopPbdOE\nEKt7Ld4zsDKGvHAOLP51QxRhjT/Km1xGJPe0yo5c4wKBgQDynEA2hfUI74Gv/cmW\nJKPpql3dIY9etw6C0PU+fUt4s7KM1ZdwqIpaAKhjfZl/sj55C1YSaEobIYGU+eN+\nuQgjeBacJi8CbEwNuCbuKxtIMd8DFv3Fifg3OUnjDmhMkYgHlTwM94D4xFg3hsSc\nNGS5IjQ3E6eQUvX7CKAc1HUfUwKBgQDv461U5vVyJ8BcmH6gnUsvNNOdKnU2g5bJ\nMvI35zkJvy3IPoMhHanaVUmIzT6zj53Di1Qq/i8q5T490niQRkdBrLHtjDBtnx7q\nahL7WccKwoVIzXNDjJBHxoNDngzuTKTSQ0SK9UrgpIMM9yubCR4FSFP2pGAwAtLZ\nrgHJ7F8puwKBgQCk5JwkMrHTa+3KLwTXPnoFs9xuEoQ+TM7ZDKrS2Rf1prUBUZ7H\nXFYETBQm4tP0XbJmVNUgV6+edwx6s8jydVJZwSIk6TLkQ7UBUhtrnvLBA9xeXj8H\nBvoklpRodX9gIz3AYabZ7VLEQbbvrnJs9JNM3Tl+AabOygQTpc4lKiWcrwKBgQDi\nfC/i7+eeLp+0DJnJJJieah68zSA7JsPPE9WSKDE23ZPo8fQ16N67bzhs+3KObzKB\nM2N07+Uyd5trHPKNLH0MKXMXlvsGFGxI33sqahm9M+hI0whXJzf1PBwkU+1bc2tN\nxQrKs0pNi6TbMeWui04XqLD1NT5HNfNCZ8HylcNHDwKBgEb4GnwnJyy8ruAO42iM\njx4yVRPXsz5h3BBJBcjJWL47DAn0hmlb7uF4dxR38dTh1z8qoZeunZw+HEnr8K+S\nLexQpJsClBo2nGTzcHqSHcM283LUjrTWurNm6hKoRlPLRCh6DFxHcMK+/6rYDHCv\n8pgAnpYp/6LPkB7YAV/4UlK/\n-----END PRIVATE KEY-----\n",
      "client_email": "alloy-logs@suncoast-systems-infra-0e1b.iam.gserviceaccount.com",
      "client_id": "104757848161497059737",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/alloy-logs%40suncoast-systems-infra-0e1b.iam.gserviceaccount.com",
      "universe_domain": "googleapis.com"
    }
