apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-logs-loki-config
  namespace: loki-logging
data:
  config.alloy: |
    discovery.kubernetes "pods" {
      role = "pod"
    }

    discovery.relabel "pods" {
      targets = discovery.kubernetes.pods.targets

      rule {
        source_labels = ["__meta_kubernetes_namespace", "__meta_kubernetes_pod_name"]
        target_label  = "namespace_pod"
        separator     = "/"
        replacement   = "$1/$2"
      }
    }

    loki.source.file "pod_logs" {
      targets    = discovery.relabel.pods.output
      forward_to = [loki.write.local.receiver]

      stages = [
        stage.labels(values = {,
          job       = "kubernetes-pod-logs",
          namespace = "{{.namespace}}",
          pod       = "{{.pod}}",
        }),
      ]
    }

    loki.write "local" {
      endpoint {
        url = "http://loki-gateway.loki-logging.svc.cluster.local/loki/api/v1/push"
      }
    }

