apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: gcp-logging-system
  labels:
    app: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      serviceAccountName: default
      containers:
        - name: fluentd
          image: gcr.io/google-containers/fluentd-gcp:1.30
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
          volumeMounts:
            - name: config-volume
              mountPath: /fluentd/etc
            - name: varlog
              mountPath: /var/log
            - name: gcp-creds
              mountPath: /var/secrets/google
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: fluentd-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: gcp-creds
          secret:
            secretName: gcp-logging-creds
